#
# Makefile - This file is part of Execution Environment.
# Copyright (c) 2013 Theobroma Systems Design and Consulting GmbH
#

# Build outside of OpenWRT?
STANDALONE?=1

TOPDIR=$(shell pwd)
SRC_DIR=$(TOPDIR)/src
TEST_DIR=$(TOPDIR)/test

CXX:=$(CROSS_COMPILE)g++
CXXFLAGS+=-Wall -Wextra -Werror -Wno-psabi -g -std=c++0x

DOXYGEN=doxygen

<% if( params.use_protobuf ) { %>
PROTOC=protoc
<% } %>


ifeq ($(STANDALONE),1)
CXXFLAGS+=-I$(STAGING_DIR)/include \
		  -I$(STAGING_DIR)/usr/include
	     
LDFLAGS+=-L$(STAGING_DIR)/lib \
		 -L$(STAGING_DIR)/usr/lib
LDFLAGS+=-Wl,-rpath-link,$(STAGING_DIR)/lib \
		 -Wl,-rpath-link,$(STAGING_DIR)/usr/lib
endif

LDFLAGS+=-Wl,-rpath-link,$(STAGING_DIR)/lib -Wl,-rpath-link,$(STAGING_DIR)/usr/lib
LDFLAGS+=-L$(OUT_LIB_DIR)

###

CP=cp -fpR
MKDIR=mkdir -p
RM=rm -f

###

export OUT_DIR CXX CXXFLAGS LDFLAGS CP MKDIR RM PROTOC

###

all: src

.PHONY: src test clean doc

src:
	$(MAKE) -C $(SRC_DIR)

test:
	$(MAKE) -C $(TEST_DIR)

doc:
	$(DOXYGEN) doc/doxygen.conf
	

clean:
	$(MAKE) -C $(SRC_DIR) clean
	$(MAKE) -C $(TEST_DIR) clean
